name: vydra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^6.3.0
  particles_flutter: ^1.0.1
  # particles_fly: ^0.0.9
  http: ^1.4.0
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.1.1
  shared_preferences: ^2.5.3
  animate_do: ^4.2.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
